path_to_original_image = "images/original/"
path_to_stego_image = "images/stego/"
path_to_difference_image = "images/difference/"
path_to_padded_image = "images/padded/"
path_to_grayscale_image = "images/grayscale/"
